let message = 'hello';
let siteName = 'owu';
let siteType = 'com';
let countryCode = 'ua';
let num1 = 1;
let num2 = 10;
let num3 = -999;
let num4 = 123;
let piValue = 3.14;
let num5 = 2.7;
let num6 = 16;
let isTrue = true;
let isFalse = false;

console.log(message);
console.log(siteName);
console.log(siteType);
console.log(countryCode);
console.log(num1);
console.log(num2);
console.log(num3);
console.log(num4);
console.log(piValue);
console.log(num5);
console.log(num6);
console.log(isTrue);
console.log(isFalse);