let arr = [42, 'текст', true, null, undefined, {name: 'Sofiia'}, [1, 2, 3], 3.14, false, Symbol('id')];
console.log(arr[0]);
console.log(arr[1]);
console.log(arr[2]);
console.log(arr[3]);
console.log(arr[4]);
console.log(arr[5]);
console.log(arr[6]);
console.log(arr[7]);
console.log(arr[8]);
console.log(arr[9]);